### PR TITLE
Fix stack state message regression

### LINKED ISSUE #102: Changes in input do not trigger a stack update
### Problem description

Once a stack is created and at the desired state, changes to the input will not trigger a stack update. 
Only changes in the commit reference to the program will or deletion of the stack

### Reproducing the issue

Create a stack, update one of the input.
Observe: no reconciliation action

### Suggestions for a fix

Seem related to these lines of code: https://github.com/pulumi/pulumi-kubernetes-operator/blob/master/pkg/controller/stack/stack_controller.go#L218

### PR DESCRIPTION
**Pull request by viveklak**
Fixes #102 and #98  which was caused due to what appears to be a regression in functionality introduced in #29.

We now record the last attempted and successful commits explicitly in their own fields in the `StackUpdateState` subresource under stack.
The original intent of reusing `StackUpdateState.State` for success and commit recording isn't clear. I have run the integration test suite locally multiple times with success which allays my fears about introducing this change given that #29 was merged to address issues demonstrated by the test suite.

In addition, we were never deleting the working directories and creating a new workspace for each reconciliation loop which resulted in #104. I considered retaining the workspace for the lifetime of the stack which might help avoid pulling down dependencies etc. multiple times. However, recreating the workspace every time seems to be more desirable than tying the lifecycle of the workspace/working directory to the stack (for determinism/reproducibility). As a result, we now delete the workspace working directory after each reconciliation - see https://github.com/pulumi/pulumi-kubernetes-operator/pull/107/commits/8bc27237f89731ab7dddc22a03918b4980438a0f. While the most desirable fix for this will come through #78, this should have a significant impact in the meantime.

**Note** that CI integration is currently failing in this repo due to recent deprecations of certain GHA commands. Working to fix those separately.

### CODE REVIEW

File: pkg/controller/stack/stack_controller.go [hunk 1]
```diff
@@ -207,20 +207,6 @@ func (r *ReconcileStack) Reconcile(request reconcile.Request) (reconcile.Result,
...
-	if err != nil {
-		sess.logger.Error(err, "Failed to get latest Stack before updating Stack", "Stack.Name", instance.Spec.Stack)
-		return reconcile.Result{}, err
-	}
-	isStackMarkedToBeDeleted = instance.GetDeletionTimestamp() != nil
-	// Don't run rest of loop if already at desired state, unless marked for deletion.
-	if !isStackMarkedToBeDeleted && (instance.Status.LastUpdate != nil && instance.Status.LastUpdate.State == instance.Spec.Commit) {
-		reqLogger.Info("Stack already at desired state", "Stack.Commit", instance.Spec.Commit)
-		return reconcile.Result{}, nil
-	}
```
Comment (lukehoban) [inline pkg/controller/stack/stack_controller.go:222]: What was the original argument for short-circuiting here?  I believe it's correct to not do this, but not sure exactly why it was added and thus not sure what potentially undesirable consequence this might have?

File: pkg/controller/stack/stack_controller.go [hunk 2]
```diff
@@ -267,8 +251,9 @@ func (r *ReconcileStack) Reconcile(request reconcile.Request) (reconcile.Result,
 			reqLogger.Error(err, "Failed to update Stack", "Stack.Name", stack.Stack)
 			// Update Stack status with failed state
 			instance.Status.LastUpdate = &pulumiv1alpha1.StackUpdateState{
-				State:     pulumiv1alpha1.FailedStackStateMessage,
-				Permalink: permalink,
+				LastAttemptedCommit: instance.Spec.Commit,
+				State:               pulumiv1alpha1.FailedStackStateMessage,
+				Permalink:           permalink,
```
Comment (lukehoban) [inline pkg/controller/stack/stack_controller.go:256]: Will this result in overwriting `lastSucceasfulCommit` to nil if it was present?

**Review by lukehoban — COMMENTED** [review]
This also fixes https://github.com/pulumi/pulumi-kubernetes-operator/issues/98 I believe, right?

File: pkg/controller/stack/stack_controller.go (hunk 2 above)
Comment (viveklak) [reply pkg/controller/stack/stack_controller.go]: Yes. Thanks for pointing out. Updated now.

File: pkg/controller/stack/stack_controller.go (hunk 1 above)
Comment (viveklak) [reply pkg/controller/stack/stack_controller.go:222]: I am not really sure on this unfortunately. One theory I have is that this was an attempt at avoiding reconciliation loops (modifying the stack CR in the reconciliation loop causes more reconciliations to trigger). #29 introduced this change and was also intended to address the reconciliation loop issue. I am running the integration tests which apparently reproduced the issues so I am hoping we can build confidence with them before pushing this change.

File: pkg/controller/stack/stack_controller.go [hunk 3]
```diff
@@ -547,6 +525,20 @@ func (sess *reconcileStackSession) SetupPulumiWorkdir(gitAuth *auto.GitAuth) err
...
+func (sess *reconcileStackSession) updateGitRevisionAtWorkingDir() error {
+	gitRepo, err := git.PlainOpen(sess.workdir)
+	if err != nil {
+		return errors.Wrapf(err, "failed to resolve git repository from working directory: %s", sess.workdir)
+	}
+	headRef, err := gitRepo.Head()
+	if err != nil {
+		return errors.Wrapf(err, "failed to determine revision for git repository at %s", sess.workdir)
+	}
+	sess.currentCommit = headRef.Hash().String()
```
Comment (lukehoban) [inline pkg/controller/stack/stack_controller.go:538]: The way we currently do all this mutation of `sess` through these various methods definitely feels a little brittle - though I recognize you are continuing with the pattern that already largely exists here.  Not sure it's worth it for a one-off here - but I could imagine this function just returning the commit (and not even being a method on the session), just to make the action-at-a-distance aspect a little less bad here.

Comment (lukehoban) [reply pkg/controller/stack/stack_controller.go:538]: Related - if we *aren't* going to do that - I would rename this to `setCurrentCommit` or something similar to be more clear on what the function does.

File: pkg/controller/stack/stack_controller.go [hunk 4]
```diff
@@ -171,6 +170,15 @@ func (r *ReconcileStack) Reconcile(request reconcile.Request) (reconcile.Result,
...
 	}
 
+	// Delete the working directory after the reconciliation is completed (regardless of success or failure).
+	defer func() {
+		if sess.workdir != "" {
+			if err := os.RemoveAll(sess.workdir); err != nil {
+				sess.logger.Error(err, "Failed to delete working dir: %s", sess.workdir)
+			}
+		}
+	}()
```
Comment (lukehoban) [inline pkg/controller/stack/stack_controller.go:180]: Minor - I wonder if we should move this into a `sess.ClosePulumiWorkdir` method and put that near `SetupPulumiWorkdir` to make the creation/destruction more cleanly coupled?

File: test/stack_controller_test.go [hunk 5]
```diff
@@ -216,7 +216,7 @@ var _ = Describe("Stack Controller", func() {
 				return false
 			}
 			if fetched.Status.LastUpdate != nil {
-				return fetched.Status.LastUpdate.State == commit
+				return fetched.Status.LastUpdate.LastSuccessfulCommit == commit
```
Comment (lukehoban) [inline test/stack_controller_test.go:219]: Are there tests we can add that cover state transitions for `lastAttemptedCommit` and `state` as well?

File: pkg/controller/stack/stack_controller.go [hunk 6]
```diff
@@ -396,25 +388,6 @@ func newReconcileStackSession(
 	}
 }
 
-// gitCloneAndCheckoutCommit clones the Git repository and checkouts the specified commit hash or branch.
-func gitCloneAndCheckoutCommit(url, hash, branch, path string) error {
```
Comment (lblackstone) [inline pkg/controller/stack/stack_controller.go:400]: Is this handled elsewhere now?

**Review by lblackstone — APPROVED** [review]

File: pkg/controller/stack/stack_controller.go (hunk 6 above)
Comment (viveklak) [reply pkg/controller/stack/stack_controller.go:400]: Yes - its done by the automation api so this was unused. See `auth.NewLocalWorkspace`.

File: pkg/controller/stack/stack_controller.go (hunk 3 above)
Comment (viveklak) [reply pkg/controller/stack/stack_controller.go]: I agree with your original statement. In general the the mutative changes are a bit heavy here. I went with the approach you outlined in your former comment.

File: test/stack_controller_test.go (hunk 5 above)
Comment (viveklak) [reply test/stack_controller_test.go]: Yup - updated now.

File: pkg/controller/stack/stack_controller.go (hunk 4 above)
Comment (viveklak) [reply pkg/controller/stack/stack_controller.go]: Agreed. Updated.

**Review by lukehoban — APPROVED** [review]
