### PR TITLE
Fix config loading

### LINKED ISSUE #183: Source repository stack config not honored
Running image version `pulumi/pulumi-kubernetes-operator:v0.0.16`

I have implemented the Pulumi K8s operator and successfully created stacks when specifying the stack config inline with the deployment spec YAML. However, I would like the stack config to be pulled from the upstream source code repository. In the crd YAML, it states:

> config:
>   additionalProperties:
>     type: string
>   description: (optional) Config is the configuration for this stack, which can be optionally specified inline. If this is omitted, configuration is assumed to be checked in and taken from the source repository.

Therefore, I removed the config block from my spec; however, the operator does not seem to be honoring the config from the source repository.

## Steps to reproduce
1. Create a stack config in the source repository.
2. Create a Pulumi stack CR using git commit sha and repository URL details of the source repository, leaving out the config section of the spec.
3. kubectl apply -f `<stack>.yml`

Expected: The upstream repository's `Pulumi.dev.yml` config would be used for the Pulumi stack CR.
Actual: `error: 1 error occurred:\n    \t* missing required configuration`

### PR DESCRIPTION
**Pull request by viveklak**
Fixes #183 

Note: This requires https://github.com/pulumi/pulumi/pull/7877 to merge and bump go.mod to pull in the SDK change.

### CODE REVIEW

File: pkg/controller/stack/stack_controller.go [hunk 1]
```diff
@@ -604,37 +604,48 @@ func (sess *reconcileStackSession) SetupPulumiWorkdir(gitAuth *auto.GitAuth) err
...
-	sess.workdir = w.WorkDir()
 
 	ctx := context.Background()
 	var a auto.Stack
 
 	if sess.stack.UseLocalStackOnly {
+		sess.logger.Info("Using local stack", "stack", sess.stack.Stack)
 		a, err = auto.SelectStack(ctx, sess.stack.Stack, w)
 	} else {
+		sess.logger.Info("Upserting stack", "stack", sess.stack.Stack, "worskspace", w)
```
Comment (lblackstone) [inline pkg/controller/stack/stack_controller.go:627]:
```suggestion
		sess.logger.Info("Upserting stack", "stack", sess.stack.Stack, "workspace", w)
```

File: test/stack_controller_test.go [hunk 2]
```diff
@@ -183,19 +184,29 @@ var _ = Describe("Stack Controller", func() {
...
 		// Local backend doesn't allow setting slashes in stack name.
-		stackName := fmt.Sprintf("%s-local-simple-stack-dev-%s", stackOrg, randString())
+		const stackName = "dev"
 		fmt.Fprintf(GinkgoWriter, "Stack.Name: %s\n", stackName)
 
 		// Tests run from outside the container. Using the safest existing directory to store
 		// local state for the sake of this test.
-		const backendDir = "/tmp"
+		backendDir, err := ioutil.TempDir("", "local-state")
+		Ω(err).ShouldNot(HaveOccurred())
```
Comment (lblackstone) [inline test/stack_controller_test.go:208]: Was the omega symbol intended?

Comment (viveklak) [reply test/stack_controller_test.go:208]: Its part of the gomega library the test framework uses: https://onsi.github.io/gomega/#making-assertions
